### ISSUE TITLE
How to "$ apt install strings" Linux command?

### ISSUE THREAD

**Issue by mrbiggleswirth** [sbingner/cydia#8]
Hi I installed "Debian Packager" via Cydia on my iPhone. I managed to "$ apt install" a couple of Linux commands which I needed for iOS pentesting exercises. But I'm having problems finding the package name for the Linux command **"strings"**.

```
root# uname -a

Darwin iPhone-5s 18.7.0 Darwin Kernel Version 18.7.0: Thu Sep 16 20:47:12 PDT 2021;
root:xnu-4903.272.4~1/RELEASE_ARM64_S5L8960X iPhone6,2 arm64 N53AP Darwin
```

I have tried these commands to investigate how to install the Linux command "strings" on my iPhone. But I'm not getting anywhere. Can somebody help me or point me in the right direction?

```
$ apt-cache search strings
$ apt-cache search binutils
$ apt-cache search utils
$ apt-cache search bin | grep strings

$ apt install coreutils
```

**Comment by sbingner** [comment]
Try odcctools I think llvm provides a strings command …. There may be another package but I don’t remember what else may provide strings off the top of my head

Sam

On Apr 18, 2022, at 11:39, mrbiggleswirth ***@***.***> wrote:

﻿

Hi I installed "Debian Packager" via Cydia on my iPhone. I managed to "$ apt install" a couple of Linux commands which I needed for iOS pentesting exercises. But I'm having problems finding the package name for the Linux command "strings".

root# uname -a

Darwin iPhone-5s 18.7.0 Darwin Kernel Version 18.7.0: Thu Sep 16 20:47:12 PDT 2021;
root:xnu-4903.272.4~1/RELEASE_ARM64_S5L8960X iPhone6,2 arm64 N53AP Darwin


I have tried these commands to investigate how to install the Linux command "strings" on my iPhone. But I'm not getting anywhere. Can somebody help me or point me in the right direction?

$ apt-cache search strings
$ apt-cache search binutils
$ apt-cache search utils
$ apt-cache search bin | grep strings

$ apt install coreutils
